print(dofile("www/opencoins/header.lua")("Home"))
print('\t\t\tOpenCoins is a global currency designed to be easy to use in CC and OC.<br>')
print('\t\t\tUsers can export coins in "tokens" which can be redeemed by anyone.<br>')
print('\t\t\tTokens are just strings, so they can be transported on things like floppies.<br><br>')
print(dofile("www/opencoins/footer.lua"))
